CREATE TABLE BAITAP3HTTT1.HANGHANGKHONG 
(
    MAHANG VARCHAR2(3) CONSTRAINT PK_HANGHANGKHONG PRIMARY KEY,
    TENHANG VARCHAR2(50),
    NGTL DATE,
    DUONGBAY NUMBER
)

CREATE TABLE BAITAP3HTTT1.CHUYENBAY 
(
    MACB VARCHAR2(6) CONSTRAINT PK_CHUYENBAY PRIMARY KEY,
    MAHANG VARCHAR2(3),
    XUATPHAT VARCHAR2(50),
    DIEMDEN VARCHAR2(50),
    BATDAU DATE,
    TGBAY NUMBER
)

CREATE TABLE BAITAP3HTTT1.NHANVIEN
(
    MANV VARCHAR2(4) CONSTRAINT PK_NHANVIEN PRIMARY KEY,
    HOTEN VARCHAR2(50),
    GIOITINH VARCHAR2(3),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR2(30)
)

CREATE TABLE BAITAP3HTTT1.PHANCONG
(
    MACB VARCHAR2(6),
    MANV VARCHAR2(4),
    NHIEMVU VARCHAR2(30),
    CONSTRAINT PK_PHANCONG PRIMARY KEY(MACB, MANV)
)

ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY HH24:MI:SS';
INSERT INTO BAITAP3HTTT1.HANGHANGKHONG VALUES ('VN', 'VIETNAME AIRLINES', '15/01/1956', '52');
INSERT INTO BAITAP3HTTT1.HANGHANGKHONG VALUES ('VJ', 'VIETJET AIR', '25/12/2011', '33');
INSERT INTO BAITAP3HTTT1.HANGHANGKHONG VALUES ('BL', 'JETSTAR PACIFIC AIRLINES', '01/12/1990', '13');
SELECT * FROM BAITAP3HTTT1.HANGHANGKHONG

INSERT INTO BAITAP3HTTT1.CHUYENBAY VALUES ('VN550', 'VN', 'TP.HCM', 'SINGAPORE', '20/12/2015 13:15', '2');
INSERT INTO BAITAP3HTTT1.CHUYENBAY VALUES ('VJ331', 'VJ', 'DA NANG', 'VINH', '28/12/2015 22:30', '1');
INSERT INTO BAITAP3HTTT1.CHUYENBAY VALUES ('BL696', 'BL', 'TP.HCM', 'DA LAT', '24/12/2015 06:00', '0.5');
SELECT * FROM BAITAP3HTTT1.CHUYENBAY

INSERT INTO BAITAP3HTTT1.NHANVIEN VALUES ('NV01','Lam Van Ben','Nam','10/09/1978','05/06/2000','Phi cong');
INSERT INTO BAITAP3HTTT1.NHANVIEN VALUES ('NV02','Duong Thi Luc','Nu','22/03/1989','12/11/2013','Tiep vien');
INSERT INTO BAITAP3HTTT1.NHANVIEN VALUES ('NV03','Hoang Thanh Tung','Nam','27/07/1983','11/04/2007','Tiep vien');
SELECT * FROM BAITAP3HTTT1.NHANVIEN

INSERT INTO BAITAP3HTTT1.PHANCONG VALUES ('VN550','NV01','Co truong');
INSERT INTO BAITAP3HTTT1.PHANCONG VALUES ('VN550','NV02','Tiep vien');
INSERT INTO BAITAP3HTTT1.PHANCONG VALUES ('BL696','NV03','Tiep vien truong');

SELECT * FROM BAITAP3HTTT1.PHANCONG
DELETE FROM BAITAP3HTTT1.PHANCONG

ALTER TABLE BAITAP3HTTT1.CHUYENBAY ADD CONSTRAINT FK_CHUYENBAY_HANGHANGKHONG FOREIGN KEY (MAHANG) REFERENCES BaiTap3HTTT1.HANGHANGKHONG(MAHANG);
ALTER TABLE BAITAP3HTTT1.PHANCONG ADD CONSTRAINT FK_PHANCONG_CHUYENBAY FOREIGN KEY (MACB) REFERENCES BaiTap3HTTT1.CHUYENBAY(MACB);
ALTER TABLE BAITAP3HTTT1.PHANCONG ADD CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES BaiTap3HTTT1.NHANVIEN(MANV);

ALTER TABLE BAITAP3HTTT1.NHANVIEN ADD CONSTRAINT CHK_CM CHECK ( CHUYENMON='Phi cong' OR CHUYENMON='Tiep vien');

SELECT *
FROM baitap3httt1.nhanvien
WHERE EXTRACT(MONTH FROM (NGSINH)) = 07

SELECT MACB
FROM BAITAP3HTTT1.phancong
GROUP BY MACB
HAVING COUNT(MANV) >= ALL (
                                SELECT COUNT(MANV)
                                FROM BAITAP3HTTT1.PHANCONG
                                GROUP BY MACB
                            )

SELECT MAHANG, COUNT(PHANCONG.MACB)
FROM BAITAP3HTTT1.PHANCONG, BAITAP3HTTT1.CHUYENBAY
WHERE CHUYENBAY.MACB= PHANCONG.MACB  AND CHUYENBAY.XUATPHAT = 'DA NANG'
GROUP BY MAHANG
HAVING COUNT(PHANCONG.MANV) < 2

SELECT * 
FROM BAITAP3HTTT1.NHANVIEN NV
WHERE NOT EXISTS ( 
                    SELECT * 
                    FROM BAITAP3HTTT1.CHUYENBAY CB
                    WHERE NOT EXISTS ( 
                                        SELECT * 
                                        FROM BAITAP3HTTT1.PHANCONG PC
                                        WHERE PC.MACB= CB.MACB AND PC.MANV= NV.MANV
                                        )
                    )


CREATE OR REPLACE TRIGGER TRG_NGAYBAY 
AFTER INSERT, UPDATE 
ON BAITAP3HTTT1.CHUYENBAY 
FOR EACH ROW 
DECLARE 
    V_NGAYTL DATE;
BEGIN 
    SELECT BAITAP3HTTT1.HANGHANGKHONG.NGTL INTO V_NGAYTL
    FROM BAITAP3HTTT1.HANGHANGKHONG
    WHERE BAITAP3HTTT1.HANGHANGKHONG.MAHANG= :NEW.MAHANG;

    IF :NEW.BATDAU <=V_NGAYTL THEN 
        RAISE_APPLICATION_ERROR(-20100,'NGAY BAT DAU CHUYEN BAY PHAI LON HON NGAY THANH LAP')
    END IF; 
END;
    