/* T?O B?NG XE*/
CREATE TABLE BaiTapHTTT1.XE
(
    MAXE VARCHAR2(3) CONSTRAINT PK_XE PRIMARY KEY,
    BIENKS VARCHAR2(10),
    MATUYEN VARCHAR(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER
)
/* T?O TUYEN XE*/
CREATE TABLE BaiTapHTTT1.TUYEN
(
    MATUYEN VARCHAR2(4) CONSTRAINT PK_TUYEN PRIMARY KEY,
    BENDAU VARCHAR(3) NOT NULL,
    BENCUOI VARCHAR(3) NOT NULL,
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK NUMBER
)
/* T?O KHÁCH HÀNG*/
CREATE TABLE BaiTapHTTT1.KHACH
(
    MAKH VARCHAR2(4) CONSTRAINT PK_KHACH PRIMARY KEY,
    HOTEN VARCHAR(20),
    GIOITINH VARCHAR(3),
    CMND NUMBER
)
/* T?O VÉ XE*/
CREATE TABLE BaiTapHTTT1.VEXE
(
    MATUYEN VARCHAR2(4),
    MAKH VARCHAR2(4),
    NGMUA DATE,
    GIAVE DECIMAL,
    CONSTRAINT PK_VEXE PRIMARY KEY(MATUYEN, MAKH, NGMUA)
)

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

INSERT INTO BaiTapHTTT1.XE VALUES ('X01', '52LD-4393', 'T11A', '20', '20');
INSERT INTO BaiTapHTTT1.XE VALUES ('X02', '59LD-7247', 'T32D', '36', '36');
INSERT INTO BaiTapHTTT1.XE VALUES ('X03', '55LD-6850', 'T06F', '15', '15');
SELECT * FROM BaiTapHTTT1.XE

INSERT INTO BaiTapHTTT1.TUYEN VALUES ('T11A', 'SG', 'DL', '210000','26/12/2016', '6');
INSERT INTO BaiTapHTTT1.TUYEN VALUES ('T32D', 'PT', 'SG', '120000','30/12/2016', '4');
INSERT INTO BaiTapHTTT1.TUYEN VALUES ('T06F', 'NT', 'DNG', '225000','02/01/2017', '6');
SELECT * FROM BaiTapHTTT1.TUYEN

INSERT INTO BaiTapHTTT1.KHACH VALUES ('KH01', 'LAM VAN BEN', 'NAM', '655615896');
INSERT INTO BaiTapHTTT1.KHACH VALUES ('KH02', 'DUONG THI LUC', 'NU', '27564862');
INSERT INTO BaiTapHTTT1.KHACH VALUES ('KH03', 'HOANG THANH TUNG', 'NAM', '456889143');
SELECT * FROM BaiTapHTTT1.KHACH

INSERT INTO BaiTapHTTT1.VEXE VALUES ('T11A', 'KH01', '20/12/2016', '210000');
INSERT INTO BaiTapHTTT1.VEXE VALUES ('T32D', 'KH02', '25/12/2016', '144000');
INSERT INTO BaiTapHTTT1.VEXE VALUES ('T06F', 'KH03', '30/12/2016', '270000');
SELECT * FROM BaiTapHTTT1.VEXE

ALTER TABLE BaiTapHTTT1.XE ADD CONSTRAINT FK_XE_TUYEN FOREIGN KEY (MATUYEN) REFERENCES BaiTapHTTT1.TUYEN(MATUYEN);
ALTER TABLE BaiTapHTTT1.VEXE ADD CONSTRAINT FK_VEXE_TUYEN FOREIGN KEY (MATUYEN) REFERENCES BaiTapHTTT1.TUYEN(MATUYEN);
ALTER TABLE BaiTapHTTT1.VEXE ADD CONSTRAINT FK_XE_KHACH FOREIGN KEY (MAKH) REFERENCES BaiTapHTTT1.KHACH(MAKH);

/*5.*/
SELECT * 
FROM BaiTapHTTT1.VEXE
WHERE EXTRACT(MONTH FROM (NGMUA))=12
ORDER BY GIAVE DESC

/*6.*/
SELECT MATUYEN
FROM BaiTapHTTT1.VEXE
WHERE EXTRACT(YEAR FROM (NGMUA)) = 2016
GROUP BY MATUYEN
HAVING COUNT(MATUYEN) <= ALL (
                                SELECT COUNT(*)
                                FROM BaiTapHTTT1.VEXE
                                WHERE EXTRACT(YEAR FROM (NGMUA)) = 2016
                                GROUP BY MATUYEN
                              ) 

/*7*/
SELECT BaiTapHTTT1.TUYEN.MATUYEN
FROM BaiTapHTTT1.TUYEN, BaiTapHTTT1.KHACH, BaiTapHTTT1.VEXE
WHERE VEXE.MAKH = KHACH.MAKH AND VEXE.MATUYEN = TUYEN.MATUYEN
AND GIOITINH='Nam'
INTERSECT
SELECT BaiTapHTTT1.TUYEN.MATUYEN
FROM BaiTapHTTT1.VEXE, BaiTapHTTT1.KHACH, BaiTapHTTT1.TUYEN
WHERE VEXE.MAKH = KHACH.MAKH AND VEXE.MATUYEN = TUYEN.MATUYEN
AND GIOITINH='Nu'

/*8.*/
SELECT * FROM BaiTapHTTT1.KHACH KH
WHERE GIOITINH = 'Nu' 
and NOT EXISTS (
                SELECT * FROM BaiTapHTTT1.TUYEN TU
                WHERE NOT EXISTS (
                                    SELECT * FROM BaiTapHTTT1.VEXE VX
                                    WHERE TU.MATUYEN = VX.MATUYEN AND KH.MAKH = VX.MAKH )
                                  )

