/*1. TAO BANG USER*/
CREATE TABLE BaiTapHTTT2.USER_NEW 
(
    U_ID VARCHAR2(3) CONSTRAINT PK_USER_NEW PRIMARY KEY,
    USERNAME VARCHAR2(20),
    PASS VARCHAR2(20),
    REGDAY DATE,
    NATIONALITY VARCHAR(20)
)

/*2. TAO BANG USER*/
CREATE TABLE BaiTapHTTT2.CHANNEL 
(
    CHANNELID VARCHAR2(4) CONSTRAINT PK_CHANNEL PRIMARY KEY,
    CNAME VARCHAR2(20),
    SUBSCRIBES NUMBER,
    OWNNER VARCHAR2(3),
    CREATED DATE
)

/*3.T?O B?NG VIDEO*/
CREATE TABLE BaiTapHTTT2.VIDEO
(
    VIDEOID VARCHAR(7) CONSTRAINT PK_VIDEO PRIMARY KEY,
    TITLE VARCHAR(100),
    DURATION NUMBER,
    AGE NUMBER
)
/*3.T?O B?NG SHARE*/
CREATE TABLE BaiTapHTTT2.SHARE_NEW
(
    VIDEOID VARCHAR(7),
    CHANNELID VARCHAR(4),
    CONSTRAINT PK_SHARE_NEW PRIMARY KEY(VIDEOID, CHANNELID)
)

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

INSERT INTO BaiTapHTTT2.USER_NEW VALUES('001', 'FAPTV', '12345ABC', '01/01/2014', 'VIET NAM');
INSERT INTO BaiTapHTTT2.USER_NEW VALUES('002', 'KEMXOITV', '@147869III', '05/06/2015', 'CAMPUCHIA');
INSERT INTO BaiTapHTTT2.USER_NEW VALUES('003', 'OPENSHARE', '12345ABC', '01/01/2014', 'VIET NAM');
SELECT * FROM BaiTapHTTT2.USER_NEW

INSERT INTO BaiTapHTTT2.CHANNEL VALUES('C120', 'FAP TV', '2343', '001', '02/01/2014');
INSERT INTO BaiTapHTTT2.CHANNEL VALUES('C905', 'KEM XOI TV', '1032', '002', '09/07/2015');
INSERT INTO BaiTapHTTT2.CHANNEL VALUES('C357', 'OPENSHARE CAFE', '5064', '003', '10/12/2010');
SELECT * FROM baitap2httt1.CHANNEL

INSERT INTO BaiTapHTTT2.VIDEO VALUES ('V100229', 'FAPTV COM NGUOI TAP 41 - DOT NHAP', '469', '18');
INSERT INTO BaiTapHTTT2.VIDEO VALUES ('V211002', 'KEM XOI: TAP 31 - MAY KOOL TINH YEU CUA ANH', '312', '16');
INSERT INTO BaiTapHTTT2.VIDEO VALUES ('V400002', 'NOI TINH YEU KET THUC - HOANG TUAN', '378', '0');
SELECT * FROM BaiTapHTTT2.VIDEO

INSERT INTO BaiTapHTTT2.SHARE_NEW VALUES ('V100229','C905');
INSERT INTO BaiTapHTTT2.SHARE_NEW VALUES ('V211002','C120');
INSERT INTO BaiTapHTTT2.SHARE_NEW VALUES ('V400002','C357');

ALTER TABLE BaiTapHTTT2.CHANNEL ADD CONSTRAINT FK_CHANNEL_USER_NEW FOREIGN KEY (OWNNER) REFERENCES BaiTapHTTT2.USER_NEW(U_ID);
ALTER TABLE BaiTapHTTT2.SHARE_NEW ADD CONSTRAINT FK_SHARE_NEW_VIDEO FOREIGN KEY (VIDEOID) REFERENCES BaiTapHTTT2.VIDEO(VIDEOID);
ALTER TABLE BaiTapHTTT2.SHARE_NEW ADD CONSTRAINT FK_SHARE_NEW_CHANNEL FOREIGN KEY (CHANNELID) REFERENCES BaiTapHTTT2.CHANNEL(CHANNELID);


/*5*/
SELECT * 
FROM BaiTapHTTT2.VIDEO
WHERE AGE >= 16

/*6*/
SELECT CNAME
FROM BaiTapHTTT2.CHANNEL
ORDER BY SUBSCRIBES DESC
FETCH FIRST 1 ROW WITH TIES

/*7*/
SELECT CHANNELID
FROM BaiTapHTTT2.SHARE_NEW, BaiTapHTTT2.VIDEO
WHERE SHARE_NEW.VIDEOID = VIDEO.VIDEOID AND AGE = 16

/*8*/
SELECT *
FROM BaiTapHTTT2.VIDEO
WHERE NOT EXISTS (
                    SELECT * 
                    FROM BaiTapHTTT2.CHANNEL
                    WHERE NOT EXISTS 
                    (
                      SELECT *
                      FROM BaiTapHTTT2.SHARE_NEW
                      WHERE SHARE_NEW.CHANNELID = CHANNEL.CHANNELID 
                      AND VIDEO.VIDEOID = SHARE_NEW.VIDEOID
                    )
                  )