CREATE TABLE BaiTapKHDL1.XE
(
    MAXE VARCHAR2(3) CONSTRAINT PK_XE PRIMARY KEY,
    BIENKS VARCHAR2(10),
    MATUYEN VARCHAR(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER
)
CREATE TABLE BaiTapKHDL1.TUYEN
(
    MATUYEN VARCHAR2(4) CONSTRAINT PK_TUYEN PRIMARY KEY,
    BENDAU VARCHAR2(3) NOT NULL,
    BENCUOI VARCHAR(3) NOT NULL,
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK NUMBER
)
CREATE TABLE BaiTapKHDL1.KHACH
(
    MAHK VARCHAR2(4) CONSTRAINT PK_KHACH PRIMARY KEY,
    HOTEN VARCHAR2(30),
    GIOITINH VARCHAR2(4),
    CMND NUMBER(9)
)
CREATE TABLE BaiTapKHDL1.VEXE
(
    MATUYEN VARCHAR2(4),
    MAHK VARCHAR2(4),
    NGMUA DATE,
    GIAVE DECIMAL,
    CONSTRAINT PK_VEXE PRIMARY KEY(MATUYEN,MAHK)
)
INSERT INTO BaiTapKHDL1.XE(MAXE, BIENKS,MATUYEN, SOGHET1, SOGHET2) VALUES('X01', '52LD-4393','T11A', 20, 20);
INSERT INTO BaiTapKHDL1.XE(MAXE, BIENKS,MATUYEN, SOGHET1, SOGHET2) VALUES('X02', '59LD-7247', 'T32D', 36, 36);
INSERT INTO BaiTapKHDL1.XE(MAXE, BIENKS,MATUYEN, SOGHET1, SOGHET2) VALUES('X03', '55LD-6850', 'T06F', 15, 15);

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';
INSERT INTO BaiTapKHDL1.TUYEN VALUES ('T11A', 'SG', 'DL', '210000','26/12/2016', '6');
INSERT INTO BaiTapKHDL1.TUYEN VALUES ('T32D', 'PT', 'SG', '120000','30/12/2016', '4');
INSERT INTO BaiTapKHDL1.TUYEN VALUES ('T06F', 'NT', 'DNG', '225000','02/01/2017', '6');

INSERT INTO BaiTapKHDL1.KHACH(MAHK, HOTEN, GIOITINH, CMND) VALUES('KH01', 'Lam Van Ben', 'Nam', 655615896);
INSERT INTO BaiTapKHDL1.KHACH(MAHK, HOTEN, GIOITINH, CMND) VALUES('KH02', 'Duong Thi Luc', 'N?', 275648642);
INSERT INTO BaiTapKHDL1.KHACH(MAHK, HOTEN, GIOITINH, CMND) VALUES('KH03', 'Hoang Thanh Tung','Nam', 456889143);

INSERT INTO BaiTapKHDL1.VEXE VALUES ('T11A','KH01','20/12/2016',210000);
INSERT INTO BaiTapKHDL1.VEXE VALUES('T32D','KH02','25/12/2016',144000);
INSERT INTO BaiTapKHDL1.VEXE VALUES('T06F','KH03','30/12/2016',270000);

ALTER TABLE BaiTapKHDL1.XE
    ADD CONSTRAINT FK_XE_TUYEN FOREIGN KEY (MATUYEN) REFERENCES BaiTapKHDL1.TUYEN(MATUYEN);
ALTER TABLE BaiTapKHDL1.VEXE
    ADD CONSTRAINT FK_VEXE_TUYEN FOREIGN KEY (MATUYEN) REFERENCES BaiTapKHDL1.TUYEN(MATUYEN);
ALTER TABLE BaiTapKHDL1.VEXE
    ADD CONSTRAINT FK_VEXE_KHACH FOREIGN KEY (MAHK) REFERENCES BaiTapKHDL1.KHACH(MAHK);
/*Cau 3*/
ALTER TABLE BaiTapKHDL1.TUYEN
ADD CHECK ((TGDK > 5 AND GIATUYEN >200000) OR TGDK <=5);
/*Cau 5*/  
SELECT * 
FROM BaiTapKHDL1.VEXE
WHERE EXTRACT(MONTH FROM (NGMUA)) = 12
ORDER BY GIAVE DESC;

/*Cau6*/
SELECT BaiTapKHDL1.TUYEN.MATUYEN, COUNT(*) AS TONGVE
FROM BaiTapKHDL1.VEXE, BaiTapKHDL1.TUYEN
WHERE BaiTapKHDL1.VEXE.MATUYEN = BaiTapKHDL1.TUYEN.MATUYEN
AND EXTRACT(YEAR FROM (NGMUA)) =  2016
GROUP BY (BaiTapKHDL1.VEXE.MATUYEN)
HAVING COUNT(*) <=  ALL(SELECT COUNT(*)
                    FROM BaiTapKHDL1.VEXE, BaiTapKHDL1.TUYEN
                    WHERE BaiTapKHDL1.VEXE.MATUYEN = BaiTapKHDL1.TUYEN.MATUYEN
                    AND EXTRACT(YEAR FROM (NGMUA)) =  2016
                    GROUP BY (BaiTapKHDL1.VEXE.MATUYEN));
 /*Cau7*/
SELECT BaiTapKHDL1.TUYEN.MATUYEN
FROM BaiTapKHDL1.VEXE, BaiTapKHDL1.TUYEN,BaiTapKHDL1.KHACH
WHERE BaiTapKHDL1.VEXE.MATUYEN = BaiTapKHDL1.TUYEN.MATUYEN
AND BaiTapKHDL1.VEXE.MAHK = BaiTapKHDL1.KHACH.MAHK
AND GIOITINH = 'Nam'
INTERSECT
SELECT BaiTapKHDL1.TUYEN.MATUYEN
FROM BaiTapKHDL1.VEXE, BaiTapKHDL1.TUYEN,BaiTapKHDL1.KHACH
WHERE BaiTapKHDL1.VEXE.MATUYEN = BaiTapKHDL1.TUYEN.MATUYEN
AND BaiTapKHDL1.VEXE.MAHK = BaiTapKHDL1.KHACH.MAHK
AND GIOITINH = 'Nu'

/*Cau 8*/
SELECT *
FROM BaiTapKHDL1.KHACH
WHERE BaiTapKHDL1.KHACH.GIOITINH = 'Nu' AND NOT EXISTS( SELECT * 
                                                        FROM BaiTapKHDL1.TUYEN
                                                        WHERE NOT EXISTS(SELECT *
                                                                        FROM BaiTapKHDL1.VEXE
                                                                        WHERE BaiTapKHDL1.VEXE.MAHK = BaiTapKHDL1.TUYEN.MATUYEN
                                                                        AND BaiTapKHDL1.VEXE.MAHK = BaiTapKHDL1.KHACH.MAHK))