/*1. TAO BANG HANGHANGKHONG*/
CREATE TABLE BAITAPHTTT3.HANGHANGKHONG 
(
    MAHANG VARCHAR2(3) CONSTRAINT PK_HANGHANGKHONG PRIMARY KEY,
    TENHANG VARCHAR2(50),
    NGTL DATE,
    DUONGBAY NUMBER
)

/*2. TAO BANG CHUYENBAY*/
CREATE TABLE BAITAPHTTT3.CHUYENBAY 
(
    MACB VARCHAR2(6) CONSTRAINT PK_CHUYENBAY PRIMARY KEY,
    MAHANG VARCHAR2(3),
    XUATPHAT VARCHAR2(50),
    DIEMDEN VARCHAR2(50),
    BATDAU DATE,
    TGBAY NUMBER
)

/*3. TAO BANG NHANVIEN*/
CREATE TABLE BAITAPHTTT3.NHANVIEN
(
    MANV VARCHAR2(4) CONSTRAINT PK_NHANVIEN PRIMARY KEY,
    HOTEN VARCHAR2(50),
    GIOITINH VARCHAR2(3),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR2(30)
)

/*4. TAO BANG PHANCONG*/
CREATE TABLE BAITAPHTTT3.PHANCONG
(
    MACB VARCHAR2(6),
    MANV VARCHAR2(4),
    NHIEMVU VARCHAR2(30),
    CONSTRAINT PK_PHANCONG PRIMARY KEY(MACB, MANV)
)

ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY HH24:MI:SS';

/*NHAP DU LIEU BANG HANGHANGKHONG*/
INSERT INTO BAITAPHTTT3.HANGHANGKHONG VALUES ('VN', 'VIETNAME AIRLINES', '15/01/1956', '52');
INSERT INTO BAITAPHTTT3.HANGHANGKHONG VALUES ('VJ', 'VIETJET AIR', '25/12/2011', '33');
INSERT INTO BAITAPHTTT3.HANGHANGKHONG VALUES ('BL', 'JETSTAR PACIFIC AIRLINES', '01/12/1990', '13');

/*NHAP DU LIEU BANG CHUYENBAY*/
INSERT INTO BAITAPHTTT3.CHUYENBAY VALUES ('VN550', 'VN', 'TP.HCM', 'SINGAPORE', '20/12/2015 13:15', '2');
INSERT INTO BAITAPHTTT3.CHUYENBAY VALUES ('VJ331', 'VJ', 'DA NANG', 'VINH', '28/12/2015 22:30', '1');
INSERT INTO BAITAPHTTT3.CHUYENBAY VALUES ('BL696', 'BL', 'TP.HCM', 'DA LAT', '24/12/2015 06:00', '0.5');

/*NHAP DU LIEU BANG NHANVIEN*/
INSERT INTO BAITAPHTTT3.NHANVIEN VALUES ('NV01','Lam Van Ben','Nam','10/09/1978','05/06/2000','Phi cong');
INSERT INTO BAITAPHTTT3.NHANVIEN VALUES ('NV02','Duong Thi Luc','Nu','22/03/1989','12/11/2013','Tiep vien');
INSERT INTO BAITAPHTTT3.NHANVIEN VALUES ('NV03','Hoang Thanh Tung','Nam','27/07/1983','11/04/2007','Tiep vien');

/*NHAP DU LIEU BANG PHANCONG*/
INSERT INTO BAITAPHTTT3.PHANCONG VALUES ('VN550','NV01','Co truong');
INSERT INTO BAITAPHTTT3.PHANCONG VALUES ('VN550','NV02','Tiep vien');
INSERT INTO BAITAPHTTT3.PHANCONG VALUES ('BL696','NV03','Tiep vien truong');

DELETE FROM BAITAPHTTT3.PHANCONG WHERE MANV = 'NV03';

ALTER TABLE BAITAPHTTT3.CHUYENBAY ADD CONSTRAINT FK_CHUYENBAY_HANGHANGKHONG FOREIGN KEY (MAHANG) REFERENCES BAITAPHTTT3.HANGHANGKHONG(MAHANG);

ALTER TABLE BAITAPHTTT3.PHANCONG ADD CONSTRAINT FK_PHANCONG_CHUYENBAY FOREIGN KEY (MACB) REFERENCES BAITAPHTTT3.CHUYENBAY(MACB);

ALTER TABLE BAITAPHTTT3.PHANCONG ADD CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES BAITAPHTTT3.NHANVIEN(MANV);

/*5. Tìm t?t c? các nhân viên có sinh nh?t trong tháng 07.*/
SELECT *
FROM BAITAPHTTT3.NHANVIEN
WHERE EXTRACT(MONTH FROM (NGSINH)) = 7

/*6. Tìm chuy?n bay có s? nhân viên nhi?u nh?t.*/
SELECT MACB
FROM BAITAPHTTT3.PHANCONG
GROUP BY MACB
HAVING COUNT(MACB) >= ALL (
                                SELECT COUNT(*)
                                FROM BAITAPHTTT3.PHANCONG
                                GROUP BY MACB
)

/*7. V?i m?i hãng hàng không, th?ng kê s? chuy?n bay có ?i?m xu?t phát là ‘?à N?ng’ và có s? nhân viên ???c phân công ít h?n 2.*/
SELECT MAHANG
FROM BAITAPHTTT3.CHUYENBAY C, BAITAPHTTT3.PHANCONG P
WHERE C.MACB = P.MACB AND XUATPHAT = 'DA NANG'
GROUP BY MAHANG
HAVING COUNT (MANV) < 2

/*8. Tìm nhân viên ???c phân công tham gia t?t c? các chuy?n bay*/
SELECT *
FROM BAITAPHTTT3.NHANVIEN N
WHERE NOT EXISTS (
    SELECT * 
    FROM BAITAPHTTT3.CHUYENBAY C
    WHERE NOT EXISTS (
        SELECT *
        FROM BAITAPHTTT3.PHANCONG P
        WHERE P.MANV = N.MANV AND P.MACB = C.MACB
    )
)