/* 1. TAO BANG XE*/
CREATE TABLE BAITAPHTTT1.XE
(
    MAXE VARCHAR2(3) CONSTRAINT PK_XE PRIMARY KEY,
    BIENKS VARCHAR2(10),
    MATUYEN VARCHAR(4),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER
)

/* 2. TAO BANG TUYEN*/
CREATE TABLE BAITAPHTTT1.TUYEN
(
    MATUYEN VARCHAR(4) CONSTRAINT PK_TUYEN PRIMARY KEY,
    BENDAU VARCHAR(3) NOT NULL,
    BENCUOI VARCHAR(3) NOT NULL,
    GIATUYEN DECIMAL,
    NGXB DATE,
    TGDK NUMBER
)

/* 3. TAO BANG KHACH*/
CREATE TABLE BAITAPHTTT1.KHACH 
(
    MAHK VARCHAR(4) CONSTRAINT PK_KHACH PRIMARY KEY,
    HOTEN VARCHAR(20),
    GIOITINH VARCHAR(3),
    CMND NUMBER(11)
)

/* 4. TAO BANG VE XE*/
CREATE TABLE BAITAPHTTT1.VEXE
(
    MATUYEN VARCHAR(4),
    MAHK VARCHAR(4),
    NGMUA DATE,
    GIAVE DECIMAL,
    CONSTRAINT PK_VEXE PRIMARY KEY(MATUYEN, MAHK, NGMUA)
)

ALTER SESSION SET NLS_DATE_FORMAT =' DD/MM/YYYY HH24:MI:SS ';

/*NHAP DU LIEU BANG XE*/
INSERT INTO BAITAPHTTT1.XE VALUES ('X01', '52LD-4393', 'T11A', '20', '20');
INSERT INTO BAITAPHTTT1.XE VALUES ('X02', '59LD-7247', 'T32D', '36', '36');
INSERT INTO BAITAPHTTT1.XE VALUES ('X03', '55LD-6850', 'T06F', '15', '15');

/*NHAP DU LIEU BANG TUYEN*/
INSERT INTO BAITAPHTTT1.TUYEN VALUES ('T11A', 'SG', 'DL', '210000','26/12/2016', '6');
INSERT INTO BAITAPHTTT1.TUYEN VALUES ('T32D', 'PT', 'SG', '120000','30/12/2016', '4');
INSERT INTO BAITAPHTTT1.TUYEN VALUES ('T06F', 'NT', 'DNG', '225000','02/01/2017', '6');

/*NHAP DU LIEU BANG KHACH*/
INSERT INTO BAITAPHTTT1.KHACH VALUES ('KH01', 'LAM VAN BEN', 'NAM', '655615896');
INSERT INTO BAITAPHTTT1.KHACH VALUES ('KH02', 'DUONG THI LUC', 'NU', '27564862');
INSERT INTO BAITAPHTTT1.KHACH VALUES ('KH03', 'HOANG THANH TUNG', 'NAM', '456889143');

/*NHAP DU LIEU BANG VEXE*/
INSERT INTO BAITAPHTTT1.VEXE VALUES ('T11A','KH01',TO_DATE('20/12/2016','DD/MM/YYYY'),210000);
INSERT INTO BAITAPHTTT1.VEXE VALUES ('T32D','KH02',TO_DATE('25/12/2016','DD/MM/YYYY'),144000);
INSERT INTO BAITAPHTTT1.VEXE VALUES ('T06F','KH03',TO_DATE('30/12/2016','DD/MM/YYYY'),270000);

ALTER TABLE BAITAPHTTT1.XE ADD CONSTRAINT FK_XE_TUYEN FOREIGN KEY (MATUYEN) REFERENCES BAITAPHTTT1.TUYEN(MATUYEN);

ALTER TABLE BAITAPHTTT1.VEXE ADD CONSTRAINT FK_VEXE_TUYEN FOREIGN KEY (MATUYEN) REFERENCES BAITAPHTTT1.TUYEN(MATUYEN);

ALTER TABLE BAITAPHTTT1.VEXE ADD CONSTRAINT FK_VEXE_KHACH FOREIGN KEY (MAHK) REFERENCES BAITAPHTTT1.KHACH(MAHK);

/*5. Tìm t?t c? các vé xe mua trong tháng 12, s?p x?p k?t qu? gi?m d?n theo giá vé.*/
SELECT *
FROM BAITAPHTTT1.VEXE
WHERE EXTRACT(MONTH FROM (NGMUA)) = 12
ORDER BY GIAVE DESC;

/*6. Tìm tuy?n xe có s? vé xe ít nh?t trong n?m 2016.*/
SELECT MATUYEN
FROM BAITAPHTTT1.VEXE
WHERE EXTRACT(YEAR FROM (NGMUA)) = 2016
GROUP BY MATUYEN
HAVING COUNT(MATUYEN) <= ALL (
                                SELECT COUNT(*)
                                FROM BAITAPHTTT1.VEXE
                                WHERE EXTRACT(YEAR FROM (NGMUA)) = 2016
                                GROUP BY MATUYEN
)

/*7. Tìm tuy?n xe có c? hành khách nam và hành khách n? mua vé.*/
SELECT T.MATUYEN
FROM BAITAPHTTT1.TUYEN T, BAITAPHTTT1.KHACH K, BAITAPHTTT1.VEXE V
WHERE V.MAHK = K.MAHK AND V.MATUYEN = T.MATUYEN AND GIOITINH='NAM'
INTERSECT
SELECT T.MATUYEN
FROM BAITAPHTTT1.TUYEN T, BAITAPHTTT1.KHACH K, BAITAPHTTT1.VEXE V
WHERE V.MAHK = K.MAHK AND V.MATUYEN = T.MATUYEN AND GIOITINH='NU'

/*8. Tìm hành khách n? ?ã t?ng mua vé t?t c? các tuy?n xe.*/
SELECT *
FROM BAITAPHTTT1.KHACH K
WHERE GIOITINH = 'NU' AND NOT EXISTS (
    SELECT *
    FROM BAITAPHTTT1.TUYEN T
    WHERE NOT EXISTS (
        SELECT *
        FROM BAITAPHTTT1.VEXE V
        WHERE K.MAHK = V.MAHK AND T.MATUYEN = V.MATUYEN
    )
)

