--3. Hi?n th?c ràng bu?c toàn v?n sau: Chuyên môn c?a nhân viên ch? ???c nh?n giá tr? là ‘Phi công’ ho?c ‘Ti?p viên’.
ALTER TABLE BAITAPHTTT3.NHANVIEN 
ADD CONSTRAINT CHK_NV_CM CHECK ( CHUYENMON='Phi cong' OR CHUYENMON='Tiep vien');

--4Hi?n th?c ràng bu?c toàn v?n sau: Ngày b?t ??u chuy?n bay luôn l?n h?n ngày thành l?p hãng hàng không qu?n lý chuy?n bay ?ó.
CREATE OR REPLACE TRIGGER TRIGGER_BATDAU_NGTL
BEFORE INSERT OR UPDATE 
ON BAITAPHTTT3.CHUYENBAY
FOR EACH ROW
DECLARE
    V_NGTL DATE;
BEGIN
    SELECT BAITAPHTTT3.HANGHANGKHONG.NGTL INTO V_NGTL
    FROM BAITAPHTTT3.HANGHANGKHONG
    WHERE BAITAPHTTT3.HANGHANGKHONG.MAHANG = :NEW.MAHANG;
    
    IF :NEW.BATDAU <= V_NGTL THEN
        RAISE_APPLICATION_ERROR(-20100, 'NGAY BAT DAU CHUYEN BAY PHAI LON HON NGAY THANH LAP HANG HANG KHONG QUAN LY CHUYEN BAY.');
    END IF;
END;
