--YEU CAU 1: 10 CAU TRUY VAN NHIEU DANG

--1. GIAO

--Tìm khách hàng ?ã mua vé tàu t?i 2 chi nhánh 'CN01' và 'CN02', thông tin hi?n th? g?m Mã khách hàng, tên khách hàng và lo?i khách hàng.

	SELECT DISTINCT A.MA_KH, HO_TEN, LOAI_KH
	FROM CN01.KHACH_HANG@DBL_CN01 A, CN01.VE@DBL_CN01 B
	WHERE A.MA_KH = B.MA_KH
	INTERSECT
	SELECT DISTINCT C.MA_KH, HO_TEN, LOAI_KH
	FROM CN02.KHACH_HANG C, CN02.VE D
	WHERE C.MA_KH = D.MA_KH;
    
--Tìm nh?ng khách hàng mua c? vé th??ng và vé tháng?

	SELECT DISTINCT *
	FROM (
		SELECT *
		FROM CN01.KHACH_HANG@DBL_CN01
		WHERE MA_KH IN(SELECT DISTINCT MA_KH
			FROM CN01.VE@DBL_CN01
			WHERE LOAI_VE = 'Ve Thuong'
			INTERSECT
			SELECT DISTINCT (MA_KH)
			FROM CN01.VE@DBL_CN01
			WHERE LOAI_VE = 'Ve Thang')
		UNION
		SELECT *
		FROM CN02.KHACH_HANG
		WHERE MA_KH IN(SELECT DISTINCT MA_KH
			FROM CN02.VE
			WHERE LOAI_VE = 'Ve Thuong'
			INTERSECT
			SELECT DISTINCT (MA_KH)
			FROM CN02.VE
			WHERE LOAI_VE = 'Ve Thang')
	);

--2. H?I

--T? t?t c? chi nhánh. Tìm ra nh?ng nhân viên (MA_NV) ?ã bán vé tháng cho khách hàng có Lo?i khách hàng là 'HS-SV'.

	SELECT C.MA_NV, C.HO_TEN, C.MA_CN
	FROM CN01.KHACH_HANG@DBL_CN01 A, CN01.VE@DBL_CN01 B, CN01.NHAN_VIEN@DBL_CN01 C
	WHERE A.MA_KH = B.MA_KH AND B.MA_NV = C.MA_NV
	AND A.LOAI_KH = 'HS-SV' AND B.LOAI_VE = 'Ve Thang'
	UNION
	SELECT F.MA_NV, F.HO_TEN, F.MA_CN
	FROM CN02.KHACH_HANG D, CN02.VE E, CN02.NHAN_VIEN F
	WHERE D.MA_KH = E.MA_KH AND E.MA_NV = F.MA_NV
	AND D.LOAI_KH = 'HS-SV' AND E.LOAI_VE = 'Ve Thang';

--3. TR?

--Tìm khách hàng (MA_KH, HO_TEN) ?ã mua vé ? chi nhánh 'CN01' mà ch?a mua vé ? chi nhanh 'CN02'.

	SELECT DISTINCT A.MA_KH, HO_TEN
	FROM  CN01.KHACH_HANG@DBL_CN01 A, CN01.VE@DBL_CN01 B
	WHERE A.MA_KH = B.MA_KH 
    	AND A.MA_KH NOT IN (
		SELECT DISTINCT MA_KH
		FROM CN02.VE
	);

--Tìm nh?ng khách hàng ch? mua vé th??ng ? c? 2 chi nhánh.

	SELECT *
	FROM CN01.KHACH_HANG@DBL_CN01
	WHERE MA_KH IN(SELECT DISTINCT(MA_KH)
		FROM CN01.VE@DBL_CN01
		MINUS
		SELECT DISTINCT(MA_KH)
		FROM CN01.VE@DBL_CN01
		WHERE LOAI_VE = 'Ve Thang')
	INTERSECT
	SELECT *
	FROM CN02.KHACH_HANG
	WHERE MA_KH IN(SELECT DISTINCT(MA_KH)
		FROM CN02.VE
		MINUS
		SELECT DISTINCT(MA_KH)
		FROM CN02.VE
		WHERE LOAI_VE = 'Ve Thang');

--4. CHIA

--Tìm các nhân viên (MA_NV, HO_TEN) ?ã bán vé cho t?t c? các khách hàng có Lo?i khách hàng là 'Nguoi khuyet tat' ? các chi nhánh.

	SELECT MA_NV, HO_TEN, MA_CN
	FROM CN01.NHAN_VIEN@DBL_CN01 A
	WHERE NOT EXISTS (
		SELECT *
		FROM CN01.KHACH_HANG@DBL_CN01 B
		WHERE B.LOAI_KH = 'Nguoi khuyet tat'
		AND NOT EXISTS (
			SELECT *
			FROM  CN01.VE@DBL_CN01 C
			WHERE A.MA_NV = C.MA_NV AND B.MA_KH = C.MA_KH
		)
	)
	UNION
	SELECT MA_NV, HO_TEN, MA_CN
	FROM CN02.NHAN_VIEN D
	WHERE NOT EXISTS (
		SELECT *
		FROM CN02.KHACH_HANG E
		WHERE E.LOAI_KH = 'Nguoi khuyet tat'
		AND NOT EXISTS (
			SELECT *
			FROM CN02.VE F
			WHERE D.MA_NV = F.MA_NV AND E.MA_KH = F.MA_KH
		)
	);

--Tìm nhân viên ?ã bán vé tàu t?t c? các tuy?n ? các chi nhánh. 

	SELECT MA_NV, HO_TEN, MA_CN
	FROM CN01.NHAN_VIEN@DBL_CN01 A
	WHERE NOT EXISTS(
    		SELECT * 
    		FROM CN01.TUYEN_TAU_NV@DBL_CN01 B
    		WHERE NOT EXISTS (
        		SELECT * 
        		FROM CN01.VE@DBL_CN01 C
        		WHERE A.MA_NV = C.MA_NV AND B.MA_TUYEN = C.MA_TUYEN
    		)
	)
	UNION             
	SELECT MA_NV, HO_TEN, MA_CN
	FROM CN02.NHAN_VIEN D
	WHERE NOT EXISTS(
    		SELECT * 
    		FROM CN02.TUYEN_TAU_NV E
    		WHERE NOT EXISTS (
        		SELECT * 
        		FROM CN02.VE F
        		WHERE D.MA_NV = F.MA_NV AND E.MA_TUYEN = F.MA_TUYEN
    		)
	);

--5. HÀM GOM NHÓM

--Tính s? l??ng Vé th??ng và Vé tháng bán ???c ? c? 2 chi nhánh.

	SELECT TEN_CN, LOAI_VE, COUNT(*) AS SL
	FROM CN01.VE@DBL_CN01 A, CN01.TUYEN_TAU_QL@DBL_CN01 B, CN01.CHI_NHANH_QL@DBL_CN01 C
	WHERE A.MA_TUYEN = B.MA_TUYEN AND B.MA_CN = C.MA_CN 
	GROUP BY TEN_CN, LOAI_VE
	UNION
	SELECT TEN_CN, LOAI_VE, COUNT(*) AS SL
	FROM CN02.VE D, CN02.TUYEN_TAU_QL E, CN02.CHI_NHANH_QL F
	WHERE D.MA_TUYEN = E.MA_TUYEN AND E.MA_CN = F.MA_CN 
	GROUP BY TEN_CN, LOAI_VE;

--6. TÍNH TOÁN

--Tính doanh thu bán vé theo th? c?a t?ng chi nhánh.

	SELECT MA_CN, TO_CHAR(NGAY_MUA, 'DAY'), SUM(TRI_GIA) AS DOANH_THU
	FROM  CN01.VE@DBL_CN01 A, CN01.TUYEN_TAU_QL@DBL_CN01 B
    	WHERE A.MA_TUYEN = B.MA_TUYEN
	GROUP BY MA_CN, TO_CHAR(NGAY_MUA, 'DAY')
	UNION
	SELECT MA_CN, TO_CHAR(NGAY_MUA, 'DAY'), SUM(TRI_GIA) AS DOANH_THU
	FROM CN02.VE C, CN02.TUYEN_TAU_QL D
    	WHERE C.MA_TUYEN = D.MA_TUYEN
	GROUP BY MA_CN, TO_CHAR(NGAY_MUA, 'DAY');

--Tìm các tuy?n tàu có ít ng??i mua nh?t ? 2 chi nhánh.

SELECT MA_TUYEN, TEN_TUYEN, MA_CN FROM CN01.TT_MIN@DBL_CN01 --Cau select nay xuat ra ket qua nhung tuyen tau co it nguoi mua o chi nhanh 1
UNION
	SELECT QL.MA_TUYEN, TEN_TUYEN, MA_CN
	FROM CN02.TUYEN_TAU_QL QL, CN02.TUYEN_TAU_NV NV
	WHERE QL.MA_TUYEN = NV.MA_TUYEN AND QL.MA_TUYEN IN(SELECT MA_TUYEN
		FROM CN02.VE
		GROUP BY MA_TUYEN
		HAVING COUNT(*) <= ALL(SELECT COUNT(*)
				FROM CN02.VE
				GROUP BY MA_TUYEN)
		);




